---
- name: Check mandatory variables
  assert:
    that:
      - server_fqdn is defined

- name: Using the following Kodo Cloud Server FQDN
  debug:
    msg: "Kodo Cloud Server FQDN: {{ server_fqdn }}, Kodo Cloud Agent name: {{ agent_name }}"

- name: Add Kodo Cloud repository
  yum_repository:
    name: kodo-cloud
    description: Kodo Cloud repo
    baseurl: "{{ kodo_repo }}"
    gpgcheck: no

- name: Add Microsoft repository
  yum_repository:
    name: Microsoft
    description: Microsoft repository
    baseurl: "{{ ms_repo_url }}"
    gpgkey: "{{ ms_repo_gpg_key }}"
    gpgcheck: yes

- name: Install Kodo Cloud Agent
  yum:
    name: kodo-cloud-agent
    state: present

- name: Initialize Kodo Cloud Agent
  shell: "{{ kodo_agent_init_script_path }} -s {{ server_fqdn }}:{{ server_port }} -n {{ agent_name }}"

- name: Start and enable Kodo Cloud Agent service
  service:
    name: kodo-cloud-agent
    daemon-reload: yes
    state: started
    enabled: yes