---
- name: Check mandatory variables
  assert:
    that:
      - server_fqdn is defined

- name: Using the following Kodo Cloud Server FQDN
  debug:
    msg: "Kodo Cloud Server FQDN: {{ server_fqdn }}, Kodo Cloud Agent name: {{ agent_name }}"

- name: Add Kodo Cloud repository
  yum_repository:
    name: kodo-cloud
    description: Kodo Cloud repo
    baseurl: "{{ kodo_repo }}"
    gpgcheck: no

- name: Add Microsoft repository
  yum_repository:
    name: Microsoft
    description: Microsoft repository
    baseurl: "{{ ms_repo_url }}"
    gpgkey: "{{ ms_repo_gpg_key }}"
    gpgcheck: yes

- name: Install Kodo Cloud Agent
  yum:
    name: kodo-cloud-agent
    state: present

- name: Initialize Kodo Cloud Agent
  shell: "{{ kodo_agent_init_script_path }} -s {{ server_fqdn }}:{{ server_port }} -n {{ agent_name }}"
  register: kodo_init_out
  failed_when:
    - kodo_init_out is failed
    - kodo_init_out.rc != 4

- name: Create staging directory
  file:
    path: "{{ kodo_staging_path }}"
    state: directory
    owner: "{{ kodo_user }}"
    group: "{{ kodo_group }}"
    mode: "0700"

- name: Start and enable Kodo Cloud Agent service
  service:
    name: "cloud-agent-{{ agent_name }}"
    daemon-reload: yes
    state: started
    enabled: yes